#!/usr/bin/env bash
set -euo pipefail

# ------------------------------------------------------------------------------
# ensure_kafka.sh (cluster, mac-compatible, KRaft-only, zero-ambiguity)
# ------------------------------------------------------------------------------

source "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/scripts/lib/_bootstrap.sh"
bootstrap cluster

# ----------------------------- tiny logger ------------------------------------
ts() { date '+%H:%M:%S'; }
kafkalog() { echo "[$(date '+%F %T')] [ensure_kafka] $*"; }
die() { echo "[$(date '+%F %T')] [ensure_kafka] ERROR: $*" >&2; exit 1; }

# ----------------------------- compat helpers ---------------------------------
is_macos() {
  [[ "$(uname -s)" == "Darwin" ]]
}

sed_inplace() {
  if is_macos; then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}

# prefer nc for cross-platform port probe; fallback to bash /dev/tcp
tcp_probe() {
  local h="$1" p="$2"

  if command -v nc >/dev/null 2>&1; then
    if is_macos; then
      nc -z -G 1 "$h" "$p" >/dev/null 2>&1
    else
      nc -z -w 1 "$h" "$p" >/dev/null 2>&1
    fi
    return $?
  fi

  bash -c "exec 3<>/dev/tcp/$h/$p" >/dev/null 2>&1
}

# ----------------------------- broker helpers ---------------------------------
broker_host() { echo "${KAFKA_BROKERS%%:*}"; }
broker_port() { echo "${KAFKA_BROKERS##*:}"; }

kafka_is_up() {
  local h p
  h="$(broker_host)"
  p="$(broker_port)"
  tcp_probe "$h" "$p"
}

kafka_wait_up() {
  local timeout="${1:-30}"
  local start now
  start="$(date +%s)"
  while true; do
    kafka_is_up && return 0
    now="$(date +%s)"
    (( now - start >= timeout )) && return 1
    sleep 0.2
  done
}

pid_alive() {
  local pid="$1"
  kill -0 "$pid" >/dev/null 2>&1
}

stop_old_kafka_tailer() {
  if [[ -f "$KAFKA_TAIL_PID_FILE" ]]; then
    local tpid
    tpid="$(cat "$KAFKA_TAIL_PID_FILE" 2>/dev/null || true)"
    if [[ -n "$tpid" ]] && pid_alive "$tpid"; then
      kafkalog "Stopping old kafka log tailer pid=$tpid"
      kill "$tpid" >/dev/null 2>&1 || true
      sleep 0.1
      pid_alive "$tpid" && kill -KILL "$tpid" >/dev/null 2>&1 || true
    fi
    rm -f "$KAFKA_TAIL_PID_FILE" >/dev/null 2>&1 || true
  fi
}

# ----------------------------- strict requirements -----------------------------
is_kraft_config() {
  grep -Eq '^[[:space:]]*process\.roles=' "$KAFKA_CONFIG"
}

resolve_kafka_topics_sh() {
  if command -v "$KAFKA_TOPICS_SH" >/dev/null 2>&1; then
    return 0
  fi
  if [[ -x "$KAFKA_HOME/bin/kafka-topics.sh" ]]; then
    KAFKA_TOPICS_SH="$KAFKA_HOME/bin/kafka-topics.sh"
    return 0
  fi
  die "kafka-topics.sh not found. Set KAFKA_TOPICS_SH or fix KAFKA_HOME/PATH."
}

ensure_project_config() {
  [[ -f "$KAFKA_CONFIG" ]] || die "Kafka config not found: $KAFKA_CONFIG"

  mkdir -p "$(dirname "$KAFKA_PROJECT_CONFIG")"
  mkdir -p "$KAFKA_PROJECT_LOG_DIR"

  cp -f "$KAFKA_CONFIG" "$KAFKA_PROJECT_CONFIG"

  sed_inplace \
    -e '/^[[:space:]]*log\.dirs[[:space:]]*=/d' \
    -e '/^[[:space:]]*log\.dir[[:space:]]*=/d' \
    -e '/^[[:space:]]*metadata\.log\.dir[[:space:]]*=/d' \
    -e '/^[[:space:]]*listeners[[:space:]]*=/d' \
    -e '/^[[:space:]]*advertised\.listeners[[:space:]]*=/d' \
    -e '/^[[:space:]]*inter\.broker\.listener\.name[[:space:]]*=/d' \
    -e '/^[[:space:]]*controller\.listener\.names[[:space:]]*=/d' \
    -e '/^[[:space:]]*controller\.quorum\.voters[[:space:]]*=/d' \
    "$KAFKA_PROJECT_CONFIG"

  {
    echo ""
    echo "# --- project overrides (generated by ensure_kafka.sh) ---"
    echo "log.dirs=$KAFKA_PROJECT_LOG_DIR"
    echo "metadata.log.dir=$KAFKA_PROJECT_LOG_DIR"
    echo "listeners=PLAINTEXT://:$KAFKA_PORT,CONTROLLER://:$KAFKA_CONTROLLER_PORT"
    echo "advertised.listeners=PLAINTEXT://$KAFKA_BROKERS"
    echo "inter.broker.listener.name=PLAINTEXT"
    echo "controller.listener.names=CONTROLLER"
    echo "controller.quorum.voters=1@localhost:$KAFKA_CONTROLLER_PORT"
  } >> "$KAFKA_PROJECT_CONFIG"

  KAFKA_CONFIG="$KAFKA_PROJECT_CONFIG"
}

require_kafka_install() {
  [[ -x "$KAFKA_SERVER_START" ]] || die "kafka-server-start.sh not found/executable: $KAFKA_SERVER_START"
  [[ -x "$KAFKA_STORAGE" ]] || die "kafka-storage.sh not found/executable: $KAFKA_STORAGE"
  resolve_kafka_topics_sh

  ensure_project_config

  [[ -f "$KAFKA_CONFIG" ]] || die "Kafka config not found: $KAFKA_CONFIG"
  is_kraft_config || die "KRaft required: process.roles not found in config: $KAFKA_CONFIG"
}

# ----------------------------- kraft format logic ------------------------------
read_config_kv() {
  local key="$1"
  grep -E "^[[:space:]]*${key}=" "$KAFKA_CONFIG" \
    | tail -n 1 \
    | sed -E "s/^[[:space:]]*${key}=//" \
    | sed -E 's/[[:space:]]+$//'
}

kraft_storage_formatted() {
  local log_dirs d
  log_dirs="$(read_config_kv 'log.dirs' || true)"
  [[ -z "$log_dirs" ]] && log_dirs="$(read_config_kv 'log.dir' || true)"
  [[ -n "$log_dirs" ]] || die "KRaft required: log.dirs/log.dir missing in $KAFKA_CONFIG"

  IFS=',' read -r -a dirs <<<"$log_dirs"
  for d in "${dirs[@]}"; do
    d="$(echo "$d" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
    [[ -z "$d" ]] && continue
    [[ -f "$d/meta.properties" ]] && return 0
  done
  return 1
}

kraft_format_if_needed() {
  if kraft_storage_formatted; then
    return 0
  fi
  kafkalog "KRaft storage not formatted; formatting..."
  local cluster_id
  cluster_id="$("$KAFKA_STORAGE" random-uuid)"
  "$KAFKA_STORAGE" format -t "$cluster_id" -c "$KAFKA_CONFIG" >/dev/null
  kafkalog "KRaft storage formatted (cluster.id=$cluster_id)"
}

# ----------------------------- start kafka ------------------------------------
kafka_start() {
  if [[ -f "$KAFKA_PID_FILE" ]]; then
    local pid
    pid="$(cat "$KAFKA_PID_FILE" 2>/dev/null || true)"
    if [[ -n "$pid" ]] && pid_alive "$pid"; then
      kafkalog "Kafka already running (pid=$pid)"
      return 0
    fi
    rm -f "$KAFKA_PID_FILE" || true
  fi

  mkdir -p "$LOG_DIR"
  kraft_format_if_needed
  stop_old_kafka_tailer

  local stamp latest hist pid
  stamp="$(date '+%Y%m%d_%H%M%S')"
  latest="$LOG_DIR/kafka.latest.log"
  hist="$LOG_DIR/kafka.$stamp.log"

  : >"$latest"
  : >"$hist"

  kafkalog "Starting Kafka (KRaft): config=$KAFKA_CONFIG"
  kafkalog "Kafka logs: latest=$latest hist=$hist"

  nohup "$KAFKA_SERVER_START" "$KAFKA_CONFIG" >"$latest" 2>&1 &
  pid=$!
  echo "$pid" >"$KAFKA_PID_FILE"
  kafkalog "Kafka started (pid=$pid)"

  nohup tail -n 0 -F "$latest" >>"$hist" 2>&1 &
  echo "$!" >"$KAFKA_TAIL_PID_FILE"
  kafkalog "Kafka log tailer started (pid=$(cat "$KAFKA_TAIL_PID_FILE"))"
}

# ----------------------------- topic ensure -----------------------------------
topic_exists() {
  local topic="$1"
  "$KAFKA_TOPICS_SH" --bootstrap-server "$KAFKA_BROKERS" --list | grep -qx "$topic"
}

ensure_topic() {
  local topic="$1" partitions="$2"
  topic_exists "$topic" && return 0
  kafkalog "Creating topic: $topic (partitions=$partitions)"
  "$KAFKA_TOPICS_SH" --bootstrap-server "$KAFKA_BROKERS" \
    --create --if-not-exists \
    --topic "$topic" \
    --partitions "$partitions" \
    --replication-factor 1 >/dev/null
}

ensure_topics() {
  ensure_topic "$KAFKA_IN_TOPIC" "$KAFKA_IN_PARTITIONS"
  ensure_topic "$KAFKA_OUT_TOPIC" "$KAFKA_OUT_PARTITIONS"
}

# ----------------------------- main -------------------------------------------
ensure_kafka_main() {
  require_kafka_install

  kafkalog "Checking broker: $KAFKA_BROKERS"
  if ! kafka_is_up; then
    kafkalog "Broker not reachable; starting Kafka..."
    kafka_start
  fi

  kafka_wait_up 30 || die "Kafka still not reachable at $KAFKA_BROKERS. Check $LOG_DIR/kafka.*.log"

  kafkalog "Broker reachable"
  ensure_topics
  kafkalog "OK"
}

ensure_kafka_main